service: mw-api

plugins:
  - serverless-plugin-scripts
#  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  logs:
    lambda:
      logFormat: JSON
      applicationLogLevel: INFO
      systemLogLevel: INFO
  logRetentionInDays: 7
  layers:
    - !Ref ApiNodeModulesLambdaLayer
#  apiGateway:
#    restApiId: ${param:restApiId}
#    restApiRootResourceId: ${param:restApiRootResourceId}

custom:
  scripts:
    hooks:
      # This hook builds the React App. It sets the environment variables for
      # the Chat and Auth APIs and then runs the build script.
      "before:esbuild-package:package": cd mw-api && yarn buildNodeLayer

layers:
  ApiNodeModules:
    package:
      artifact: mw-api/layers/layer-node_modules.zip

functions:
  - ${file(serverless/functions/helloWorld.yml)}
